version: "3"
services:
  chafouin-server:
    build: ./chafouin-server
    working_dir: /usr/src/app
    restart: always
    environment:
      - TORRC_DIR=/etc/tor
      - TOR_DIR=/var/lib
    volumes:
      - ./chafouin-server:/usr/src/app
      - ./chafouin-shared:/usr/src/chafouin-shared
    expose:
      - "8080:8080"
    command: "npm start"
  chafouin-telegram:
    image: "node:20-alpine"
    user: "node"
    working_dir: /usr/src/app
    restart: always
    volumes:
      - ./chafouin-telegram:/usr/src/app
      - ./chafouin-shared:/usr/src/chafouin-shared
    command: "npm start"