version: "3"

services:
  api:
    build: 
      dockerfile: ./services/api/Dockerfile
      context: .
    restart: always
    environment:
      - TOR_CONFIG_DIR=/etc/tor
      - TOR_DATA_DIR=/etc/tor
      - RAILWAYS_PROVIDER_MODULE=@chafouin/uzrailways
    ports:
      - "8080:8080"
      - "9229:9229"
  telegram:
    build: 
      dockerfile: ./services/telegram/Dockerfile
      context: .
    env_file:
      - .env
    environment:
      - SCRAPER_BASE_URL=http://api:8080
    ports: 
      - "9230:9229"
    restart: always
  telegram-cache:
    image: redis/redis-stack-server:6.2.6-v7
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - telegram-cache:/data
volumes:
  telegram-cache:
    driver: local